# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZXPLocationDome' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZXPLocationDome

  #pod ‘QShare’
  #pod 'Diplomat'
  #pod 'Diplomat/Wechat'
  #pod 'Diplomat/QQ'

  target 'ZXPLocationDomeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZXPLocationDomeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
